workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

cache:
  paths:
    - target/release/build
    - target/release/deps

stages:
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/lastfm-discord-presence/$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  image: rust:latest

  script:
    - cargo build --release --verbose
  artifacts:
    paths:
      - target/release/lastfm-discord-presence


upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file target/release/lastfm-discord-presence "${PACKAGE_REGISTRY_URL}/lastfm-discord-presence"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Running the release job."
  release:
    name: 'Release for $CI_COMMIT_SHORT_SHA'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    description: 'Release created for commit $CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'Linux executable'
          url: '${PACKAGE_REGISTRY_URL}/lastfm-discord-presence'